### ISSUE TITLE
Hacktober - Fest Opportunity

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/Host-Html-Files#1]
**What Can you Do?**
Choose any from below..

- Update readme.md file add description , how one can clone
- Improve UI.
- Add any new feature if you can.

Every PR will be Appreciated.
Star the PR and Share it with your Friends.

Thankyou.

**Comment by timothyouano** [comment]
I can help with the Readme.md and some UI improvements eventually

**Comment by Rhydium** [comment]
I'll try to help with the UI and look what I can do about the features :)
